server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      httpclient:
        connect-timeout: 2000
        response-timeout: 5s

      routes:
        - id: auth-service
          uri: http://localhost:8089
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=0

        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=0

        - id: ai-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/ai/**
          filters:
            - StripPrefix=0

# JWT
app:
  jwt:
    secret: VGhpcyBpcyBhIHNlY3VyZSBzaWduaW5nIGtleSBmb3IgUE9SVEZPTElPIEFJIGF1dGggc2VydmljZSBKV1QgdG9rZW4gc2lnbmluZyBrZXk=

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
