server:
  port: 0

spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 2000
        response-timeout: 3s

      routes:
        - id: auth-service
          uri: http://localhost:8089
          predicates:
            - Path=/api/auth/**

        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**

        - id: ai-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/ai/**

app:
  jwt:
    secret: VGhpcyBpcyBhIHNlY3VyZSBzaWduaW5nIGtleSBmb3IgUE9SVEZPTElPIEFJIGF1dGggc2VydmljZSBKV1QgdG9rZW4gc2lnbmluZyBrZXk=

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
